Industry Ready Production Analysis

In [4]:
import pandas as pd
csv_movies = pd.read_csv(r"c:\Users\vaishnavi\Downloads\imdb-top-1000 (2) (3).csv") #copy path se liya ye file copy kar ke
csv_movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539,93.0

*******business problem data analysis logic code and answer business interpretation*******
1)(company ko kya cahiye)business problem
2)(data analysis logic #konse column aur pandas operations)
3)(code and answer #result display)
4)business interuption=>result=>basis=>decision data limitation

In [5]:
#problem--1)Audiance engagement
#which movie have the strongest audiance engagement signal in this data set
csv_movies.nlargest(10,"No_of_Votes")[["Series_Title","Genre","IMDB_Rating","No_of_Votes"]]

,Series_Title,Genre,IMDB_Rating,No_of_Votes
0,The Shawshank Redemption,Drama,9.3,2343110
2,The Dark Knight,Action,9.0,2303232
8,Inception,Action,8.8,2067042
9,Fight Club,Drama,8.8,1854740
6,Pulp Fiction,Crime,8.9,1826188
11,Forrest Gump,Drama,8.8,1809221
14,The Matrix,Action,8.7,1676426
10,The Lord of the Rings: The Fellowship of the Ring,Action,8.8,1661481
5,The Lord of the Rings: The Return of the King,Action,8.9,1642758
1,The Godfather,Crime,9.2,1620367

In [7]:
#problem--2)High Quality Movies Shortlist
#find movies with rating at least  8.5 and at least 100,000
shortlist=csv_movies[(csv_movies["IMDB_Rating"]>=8.5)&(csv_movies["No_of_Votes"]>=100000)]
shortlist[["Series_Title","IMDB_Rating","No_of_Votes"]]

,Series_Title,IMDB_Rating,No_of_Votes
0,The Shawshank Redemption,9.3,2343110
1,The Godfather,9.2,1620367
2,The Dark Knight,9.0,2303232
3,The Godfather: Part II,9.0,1129952
4,12 Angry Men,9.0,689845
5,The Lord of the Rings: The Return of the King,8.9,1642758
6,Pulp Fiction,8.9,1826188
7,Schindler's List,8.9,1213505
8,Inception,8.8,2067042
9,Fight Club,8.8,1854740
10,The Lord of the Rings: The Fellowship of the Ring,8.8,1661481
11,Forrest Gump,8.8,1809221
12,"Il buono, il brutto, il cattivo",8.8,688390
13,The Lord of the Rings: The Two Towers,8.7,1485555
14,The Matrix,8.7,1676426
15,Goodfellas,8.7,1020727
16,Star Wars: Episode V - The Empire Strikes Back,8.7,1159315
17,One Flew Over the Cuckoo's Nest,8.7,918088
19,Gisaengchung,8.6,552778
21,Interstellar,8.6,1512360
22,Cidade de Deus,8.6,699256
23,Sen to Chihiro no kamikakushi,8.6,651376
24,Saving Private Ryan,8.6,1235804
25,The Green Mile,8.6,1147794
26,La vita è bella,8.6,623629
27,Se7en,8.6,1445096
28,The Silence of the Lambs,8.6,1270197
29,Star Wars,8.6,1231473
31,Shichinin no samurai,8.6,315744
32,It's a Wonderful Life,8.6,405801
33,Joker,8.5,939252
34,Whiplash,8.5,717585
35,The Intouchables,8.5,760360
36,The Prestige,8.5,1190259
37,The Departed,8.5,1189773
38,The Pianist,8.5,729603
39,Gladiator,8.5,1341460
40,American History X,8.5,1034705
41,The Usual Suspects,8.5,991208
42,Léon,8.5,1035236
43,The Lion King,8.5,942045
44,Terminator 2: Judgment Day,8.5,995506
45,Nuovo Cinema Paradiso,8.5,230763
46,Hotaru no haka,8.5,235231
47,Back to the Future,8.5,1058081
48,Once Upon a Time in the West,8.5,302844
49,Psycho,8.5,604211
50,Casablanca,8.5,522093
51,Modern Times,8.5,217881
52,City Lights,8.5,167839

In [10]:
#problem--3) Genre performnce report
#which genre have high ratings, longer runtimes and more audiance votes
#(logic,gpyb,agg,max,mean,sum)


genre_report = csv_movies.groupby("Genre").agg(
    Movie_Count=("Series_Title", "count"),
    Average_Rating=("IMDB_Rating", "mean"),
    Median_Rating=("IMDB_Rating", "median"),
    Average_Runtime=("Runtime", "mean"),
    Total_Votes=("No_of_Votes", "sum")
)

genre_report.sort_values(
    "Average_Rating", ascending=False
)

,Movie_Count,Average_Rating,Median_Rating,Average_Runtime,Total_Votes
Genre,,,,,
Western,4,8.350000,8.4,148.250000,1289665
Crime,107,8.016822,8.0,126.392523,33533615
Fantasy,2,8.000000,8.0,85.000000,146222
Mystery,12,7.975000,8.0,119.083333,4203004
Film-Noir,3,7.966667,8.0,104.000000,367215
Drama,289,7.957439,8.0,124.737024,61367304
Action,172,7.949419,7.9,129.046512,72282412
Biography,88,7.938636,7.9,136.022727,24006844
Adventure,72,7.937500,7.9,134.111111,22576163
Animation,82,7.930488,7.9,99.585366,21978630
Horror,11,7.909091,7.8,102.090909,3742556
Comedy,155,7.901290,7.9,112.129032,27620327
Family,2,7.800000,7.8,107.500000,551221
Thriller,1,7.800000,7.8,108.000000,27733

In [12]:
#[10/10, 4:02 PM] Agent Ops: #uses of the data buget,marketing,revenue,audience views
#[10/10, 4:03 PM] Agent Ops: #as datasciencest---
#higher imdb ratings associated with higher vote counts
csv_movies[["IMDB_Rating","No_of_Votes"]].corr()
#corr()do numerical columns ke values ek dusare ke sath kis taraha related hai
#dono column ke beech corr calculate karke ek table return karta hai

             IMDB_Rating  No_of_Votes
IMDB_Rating     1.000000     0.494979
No_of_Votes     0.494979     1.000000